//спецификация исключений

void func(int a) throw(x2, x3);